#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

services:

  orderer.logistics.com:
    container_name: orderer.logistics.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/logistics.com/orderers/orderer.logistics.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/logistics.com/orderers/orderer.logistics.com/tls/:/var/hyperledger/orderer/tls
    - orderer.logistics.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.exporterorg.logistics.com:
    container_name: peer0.exporterorg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exporterorg.logistics.com
      - CORE_PEER_ADDRESS=peer0.exporterorg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exporterorg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exporterorg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporterorg.logistics.com/peers/peer0.exporterorg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exporterorg.logistics.com/peers/peer0.exporterorg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exporterorg.logistics.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

  peer0.importerorg.logistics.com:
    container_name: peer0.importerorg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.importerorg.logistics.com
      - CORE_PEER_ADDRESS=peer0.importerorg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.importerorg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.importerorg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importerorg.logistics.com/peers/peer0.importerorg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importerorg.logistics.com/peers/peer0.importerorg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.importerorg.logistics.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  peer0.carrierorg.logistics.com:
    container_name: peer0.carrierorg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.carrierorg.logistics.com
      - CORE_PEER_ADDRESS=peer0.carrierorg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.carrierorg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.carrierorg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=CarrierOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/carrierorg.logistics.com/peers/peer0.carrierorg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/carrierorg.logistics.com/peers/peer0.carrierorg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.carrierorg.logistics.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
      - 9055:6060

  peer0.regulatororg.logistics.com:
    container_name: peer0.regulatororg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regulatororg.logistics.com
      - CORE_PEER_ADDRESS=peer0.regulatororg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulatororg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulatororg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulatororg.logistics.com/peers/peer0.regulatororg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulatororg.logistics.com/peers/peer0.regulatororg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.regulatororg.logistics.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
      - 10055:6060

  peer0.importerbankorg.logistics.com:
    container_name: peer0.importerbankorg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.importerbankorg.logistics.com
      - CORE_PEER_ADDRESS=peer0.importerbankorg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.importerbankorg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.importerbankorg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=ImporterbankOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importerbankorg.logistics.com/peers/peer0.importerbankorg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importerbankorg.logistics.com/peers/peer0.importerbankorg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.importerbankorg.logistics.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
      - 11055:6060

  peer0.exporterbankorg.logistics.com:
    container_name: peer0.exporterbankorg.logistics.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exporterbankorg.logistics.com
      - CORE_PEER_ADDRESS=peer0.exporterbankorg.logistics.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exporterbankorg.logistics.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exporterbankorg.logistics.com:7051
      - CORE_PEER_LOCALMSPID=ExporterbankOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporterbankorg.logistics.com/peers/peer0.exporterbankorg.logistics.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exporterbankorg.logistics.com/peers/peer0.exporterbankorg.logistics.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exporterbankorg.logistics.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
      - 12055:6060